global:
  scrape_interval: 15s
  evaluation_interval: 15s
storage:
  tsdb:
    out_of_order_time_window: 10m
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "pushgateway"
    static_configs:
      - targets: ["host.docker.internal:9091"]
    scrape_interval: 5s
    honor_labels: true