name: Communication
on:
  push:
    branches: [main]
    paths:
      - 'communication/**'
      - '.github/workflows/communication.yml'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        type: choice
        options:
          - land
          - live
        default: 'land'
jobs:
  build-and-push:
    uses: ./.github/workflows/reusable-docker-build.yml
    with:
      service_name: communication
      environment: ${{ github.event.inputs.environment }}
      context_path: ./communication
      install_dependencies: true
      dependency_path: communication
    secrets:
      DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      DOCKER_USERNAME: canmingir
