name: Grafana
on:
  push:
    branches: [main]
    paths:
      - 'monitoring/grafana/**'
      - '.github/workflows/grafana.yml'
  workflow_dispatch:

jobs:
  build-and-push-land:
    uses: ./.github/workflows/reusable-docker-build.yml
    with:
      service_name: grafana
      environment: land
      context_path: ./monitoring/grafana
    secrets:
      DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      DOCKER_USERNAME: canmingir

  build-and-push-live:
    uses: ./.github/workflows/reusable-docker-build.yml
    with:
      service_name: grafana
      environment: live
      context_path: ./monitoring/grafana
    secrets:
      DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      DOCKER_USERNAME: canmingir