name: Grafana
on:
  push:
    branches: [main]
    paths:
      - 'monitoring/grafana/**'
      - '.github/workflows/grafana.yml'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        type: choice
        options:
          - land
          - live
        default: 'land'

jobs:
  build-and-push:
    uses: ./.github/workflows/deploy.yml
    with:
      service_name: grafana
      environment: ${{ github.event.inputs.environment }}
      context_path: ./monitoring/grafana
    secrets:
      DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      DOCKER_USERNAME: canmingir