name: GreyCollar
on:
  push:
    branches: [main]
    paths:
      - 'dashboard/**'
      - 'api/**'
      - '.github/workflows/greycollar.yml'
  workflow_dispatch:

jobs:
  build-and-push-land:
    uses: ./.github/workflows/reusable-docker-build.yml
    with:
      service_name: greycollar
      environment: land
      context_path: .
      install_dependencies: true
      dependency_path: .
      run_lint: true
      run_build: true
      setup_config: true
    secrets:
      DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      DOCKER_USERNAME: canmingir

  build-and-push-live:
    uses: ./.github/workflows/reusable-docker-build.yml
    with:
      service_name: greycollar
      environment: live
      context_path: .
      install_dependencies: true
      dependency_path: .
      run_lint: true
      run_build: true
      setup_config: true
    secrets:
      DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      DOCKER_USERNAME: canmingir