name: Prometheus
on:
  push:
    branches: [main]
    paths:
      - 'monitoring/prometheus/**'
      - '.github/workflows/prometheus.yml'
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        type: choice
        options:
          - land
          - live
        default: 'land'

jobs:
  build-and-push:
    uses: ./.github/workflows/reusable-docker-build.yml
    with:
      service_name: prometheus
      environment: ${{ github.event.inputs.environment }}
      context_path: ./monitoring/prometheus
    secrets:
      DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      DOCKER_USERNAME: canmingir