name: Prometheus
on:
  push:
    branches: [main]
    paths:
      - 'monitoring/prometheus/**'
      - '.github/workflows/prometheus.yml'
  workflow_dispatch:

jobs:
  build-and-push-land:
    uses: ./.github/workflows/reusable-docker-build.yml
    with:
      service_name: prometheus
      environment: land
      context_path: ./monitoring/prometheus
    secrets:
      DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      DOCKER_USERNAME: canmingir

  build-and-push-live:
    uses: ./.github/workflows/reusable-docker-build.yml
    with:
      service_name: prometheus
      environment: live
      context_path: ./monitoring/prometheus
    secrets:
      DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      DOCKER_USERNAME: canmingir